#!/usr/bin/env python3
"""Generate agent-readable doc indexes: docs/llms.txt and docs/llms-full.txt.

Reads the nav from mkdocs.yml and emits:
  - docs/llms.txt       llms.txt-format index linking the raw markdown of every page
  - docs/llms-full.txt  every page concatenated into one file

Universal contract: dry-run by default; --apply writes; --check exits 1 if the
generated files are stale (for CI); one JSON event to stderr; exit 0 on success,
1 on error.

Usage:
  python3 scripts/build_llms_txt.py            # dry-run: show what would be written
  python3 scripts/build_llms_txt.py --apply    # write docs/llms.txt + docs/llms-full.txt
  python3 scripts/build_llms_txt.py --check    # verify committed files are current
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MKDOCS = REPO / "mkdocs.yml"
DOCS = REPO / "docs"
OUT_INDEX = DOCS / "llms.txt"
OUT_FULL = DOCS / "llms-full.txt"
RAW_BASE = "https://raw.githubusercontent.com/btekmen/memexlab-engine/main/docs/"

SITE_NAME = "MemexLab Engine"
SITE_DESC = (
    "The governed memory layer for AI agents — local-first, citable, auditable. "
    "A plain-markdown vault framework: deterministic retrieval with [[slug]] "
    "citations, agent writes only into inbox/ with provenance and a JSONL log."
)


def parse_nav(text):
    """Extract (section, title, path) rows from the mkdocs nav block.

    The nav is simple two/three-level 'Title: path.md' YAML; a line-based parse
    keeps this script dependency-free.
    """
    lines = text.splitlines()
    try:
        start = next(i for i, l in enumerate(lines) if l.strip() == "nav:")
    except StopIteration:
        raise SystemExit("error: no nav: block found in mkdocs.yml")
    rows, section = [], ""
    for line in lines[start + 1:]:
        if line.strip() and not line.startswith(" "):
            break  # left the nav block
        m = re.match(r"\s+-\s+(?:\"([^\"]+)\"|'([^']+)'|([^:]+)):\s*(\S+\.md)\s*$", line)
        if m:
            title = next(g for g in m.groups()[:3] if g)
            rows.append((section, title.strip(), m.group(4)))
            continue
        m = re.match(r"\s+-\s+([^:]+):\s*$", line)
        if m:
            section = m.group(1).strip()
    return rows


def build_index(rows):
    out = [f"# {SITE_NAME}", "", f"> {SITE_DESC}", ""]
    out.append(
        "Every page below links its raw markdown source. Generated by "
        "scripts/build_llms_txt.py from mkdocs.yml — do not edit by hand."
    )
    current = None
    for section, title, path in rows:
        label = section or "Home"
        if label != current:
            out += ["", f"## {label}", ""]
            current = label
        out.append(f"- [{title}]({RAW_BASE}{path})")
    out.append("")
    return "\n".join(out)


def build_full(rows):
    out = [f"# {SITE_NAME} — full documentation", "", f"> {SITE_DESC}", ""]
    for _, title, path in rows:
        page = DOCS / path
        try:
            body = page.read_text(encoding="utf-8")
        except FileNotFoundError:
            raise SystemExit(f"error: nav references missing page: docs/{path}")
        out += ["", "---", "", f"<!-- {title} · docs/{path} -->", "", body.rstrip(), ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true", help="write the files")
    ap.add_argument("--check", action="store_true", help="exit 1 if files are stale")
    args = ap.parse_args()

    rows = parse_nav(MKDOCS.read_text(encoding="utf-8"))
    index, full = build_index(rows), build_full(rows)
    targets = {OUT_INDEX: index, OUT_FULL: full}

    if args.check:
        stale = [
            str(p.relative_to(REPO)) for p, content in targets.items()
            if not p.exists() or p.read_text(encoding="utf-8") != content
        ]
        ok = not stale
        mode = "check"
        written = []
    elif args.apply:
        for p, content in targets.items():
            p.write_text(content, encoding="utf-8")
        ok, mode, written, stale = True, "apply", [str(p.relative_to(REPO)) for p in targets], []
    else:
        ok, mode, written, stale = True, "dry-run", [], []
        print(f"dry-run: would write {OUT_INDEX.relative_to(REPO)} "
              f"({len(index.splitlines())} lines, {len(rows)} pages) and "
              f"{OUT_FULL.relative_to(REPO)} ({len(full.splitlines())} lines). "
              f"Use --apply to write.")

    print(json.dumps({"cmd": "build_llms_txt", "mode": mode, "pages": len(rows),
                      "written": written, "stale": stale, "ok": ok}), file=sys.stderr)
    if not ok:
        print(f"stale: {', '.join(stale)} — run: python3 scripts/build_llms_txt.py --apply")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
